admin:
  categories:
    per_page: 5
  users:
    per_page: 5
  posts:
    per_page: 5
    normal_post: 0
    audio_post: 1
    accept: "Accept"
    reject: "Reject"
  advertisments:
    per_page: 5
  confessions:
    per_page: 5
    length_read_more: 30
  format_date_time: "%m/%d/%Y at %I:%M%p"
time_format:
  normal: "%H:%M %d-%m-%Y"
per_page: 10
static_pages:
  number_hot_posts: 5
  number_category_posts: 5
  truncate_post_description: 100
  truncate_post_title: 70
  truncate_first_post_description: 300
  home:
    favourite_posts_size: 5
users:
  posts:
    per_page: 10
categories:
  posts:
    per_page: 6
avatar_admin: "200x200"
confessions:
    per_page: 5
